- modules/front-end/.dockerignore
- modules/front-end/Dockerfile
- modules/front-end/package.json
Make the docker image build process cleaner and more smoothie
> ✨ Improve the UI docker process

- modules/front-end/README.md
- modules/front-end/package.json
- modules/front-end/src/app/app.component.html
- modules/front-end/src/app/app.module.ts
- modules/front-end/src/app/features/login/do-login/do-login.component.html
- modules/front-end/src/app/features/login/do-login/do-login.component.ts
- modules/front-end/src/app/features/login/login.component.html
- modules/front-end/src/app/features/login/login.component.less
- modules/front-end/src/app/features/login/login.module.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> ✨Implement the login module

- README.md
> 📖 Read me typo

- modules/front-end/nginx.conf
- modules/front-end/package.json
- modules/front-end/src/app/shared/locale-switcher/locale-switcher.component.ts
Fix for the issue https://github.com/featbit/featbit/issues/11
> 🐛 Fixed the issue when trailing slash is not present after the language code

- modules/front-end/src/app/core/components/locale-switcher/locale-switcher.component.ts
- modules/front-end/src/app/core/components/menu/menu.component.html
- modules/front-end/src/app/core/components/menu/menu.component.ts
- modules/front-end/src/app/features/safe/experiments/experiments-routing.module.ts
- modules/front-end/src/app/features/safe/segments/details/details-routing.module.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> ✨feat(ui/i18n): added locale switcher for logged in pages

- modules/front-end/src/styles.less
Fix for bug https://github.com/featbit/featbit/issues/16
> 🐛Removed the second close button on modal

- modules/front-end/src/app/core/components/target-user-v2/target-user-v2.component.less
Fixed bug for https://github.com/featbit/featbit/issues/17
> 🐛 Fixed mal positioned close button on target user

- modules/front-end/Dockerfile
- modules/front-end/README.md
- modules/front-end/src/environments/environment.prod.ts
- modules/front-end/src/environments/environment.ts
> ✨Added api url as build parameter for docker

- modules/evaluation-server/src/Api/Middlewares/StreamingMiddleware.cs
- modules/evaluation-server/src/Domain/Core/Token.cs
- modules/evaluation-server/src/Domain/Core/TokenNumber.cs
- modules/evaluation-server/src/Domain/WebSockets/Connection.cs
- modules/evaluation-server/src/Domain/WebSockets/ConnectionStore.cs
- modules/evaluation-server/src/Domain/WebSockets/ConnectionType.cs
- modules/evaluation-server/src/Domain/WebSockets/ConnectionVersion.cs
- modules/evaluation-server/src/Domain/WebSockets/RequestHandler.cs
- modules/evaluation-server/src/Domain/WebSockets/Version.cs
- modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ConnectionTests.cs
- modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/StreamingTestApp.cs
- modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ValidationTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/Core/TokenNumberTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/Core/TokenTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionStoreTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionTypeTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/WebSockets/RequestHandlerTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/WebSockets/VersionTests.cs
1. separate Streaming folder into WebSockets  and Core folders
2. rename version to ConnectionVersion
> 🧹 Some Refactor On Streaming

- docker-compose-dev.yml
> ✨ feat(ui/docker-compose): added ui to docker compose

- modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
- modules/back-end/src/Api/Setup/ServicesRegister.cs
- modules/back-end/src/Api/appsettings.json
> ✨ Api add cors support

- modules/front-end/src/styles.less
Fix for https://github.com/featbit/featbit/issues/53
> 🐛 Fix (UI): fixed pagination button position

- modules/front-end/angular.json
- modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
- modules/front-end/src/app/core/components/find-rule/serve-multistates/serve-multistates.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> multi-language ff.components.details.targeting html text 

- infra/mongodb/docker-entrypoint-initdb.d/seed.js
- modules/back-end/src/Api/Controllers/EndUserController.cs
- modules/back-end/src/Api/Controllers/EndUserPropertyController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/EndUsers/DeleteEndUserProperty.cs
- modules/back-end/src/Application/EndUsers/EndUserFilter.cs
- modules/back-end/src/Application/EndUsers/GetEndUser.cs
- modules/back-end/src/Application/EndUsers/GetEndUserByKeyIds.cs
- modules/back-end/src/Application/EndUsers/GetEndUserList.cs
- modules/back-end/src/Application/EndUsers/GetEndUserProperties.cs
- modules/back-end/src/Application/EndUsers/UpsertEndUser.cs
- modules/back-end/src/Application/EndUsers/UpsertEndUserProperty.cs
- modules/back-end/src/Application/Services/IEndUserService.cs
- modules/back-end/src/Domain/EndUsers/EndUser.cs
- modules/back-end/src/Domain/EndUsers/EndUserCustomizedProperty.cs
- modules/back-end/src/Domain/EndUsers/EndUserPresetValue.cs
- modules/back-end/src/Domain/EndUsers/EndUserProperty.cs
- modules/back-end/src/Infrastructure/Bases/MongoDbServiceBase.cs
- modules/back-end/src/Infrastructure/ConfigureServices.cs
- modules/back-end/src/Infrastructure/EndUsers/EndUserService.cs
- modules/back-end/src/Infrastructure/MongoDb/MongoDbClient.cs
- modules/back-end/tests/Application.IntegrationTests/Snapshots/UserControllerTests.GetUserProfile.verified.txt
new api added:
1. end-user
- get by id
- get list by envId
- upsert end-user
- get end-user by keyIds
2. end-user property
- get all properties
- upsert property
- delete property
> ✨ add end-user related api

- infra/mongodb/docker-entrypoint-initdb.d/seed.js
- modules/back-end/src/Api/Controllers/DataSyncController.cs
- modules/back-end/src/Api/Controllers/EnvironmentSettingController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/ConfigureServices.cs
- modules/back-end/src/Application/DataSync/DownloadSyncData.cs
- modules/back-end/src/Application/DataSync/SyncToRemote.cs
- modules/back-end/src/Application/DataSync/UploadSyncData.cs
- modules/back-end/src/Application/Environments/DeleteSetting.cs
- modules/back-end/src/Application/Environments/GetSettings.cs
- modules/back-end/src/Application/Environments/UpsertSetting.cs
- modules/back-end/src/Application/Services/IDataSyncService.cs
- modules/back-end/src/Application/Services/IEnvironmentService.cs
- modules/back-end/src/Domain/DataSync/EndUserSyncData.cs
- modules/back-end/src/Domain/DataSync/RemoteSyncPayload.cs
- modules/back-end/src/Domain/DataSync/SyncData.cs
- modules/back-end/src/Domain/EndUsers/EndUser.cs
- modules/back-end/src/Domain/Environments/Environment.cs
- modules/back-end/src/Domain/Environments/Setting.cs
- modules/back-end/src/Domain/Environments/SettingTypes.cs
- modules/back-end/src/Domain/Utils/ReusableJsonSerializerOptions.cs
- modules/back-end/src/Infrastructure/ConfigureServices.cs
- modules/back-end/src/Infrastructure/DataSync/DataSyncService.cs
- modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
new apis:
1. local sync
2. environment setting
4. remote sync
> ✨ Data Sync

- modules/evaluation-server/src/Api/Public/InsightController.cs
- modules/evaluation-server/src/Api/Public/PublicApiControllerBase.cs
- modules/evaluation-server/src/Domain/Core/Topics.cs
- modules/evaluation-server/src/Domain/Insights/Insight.cs
- modules/evaluation-server/src/Domain/Insights/InsightMessage.cs
- modules/evaluation-server/src/Domain/Insights/MetricInsight.cs
- modules/evaluation-server/src/Domain/Insights/VariationInsight.cs
add track insight api in evaluation server
> ✨ Track Insights Api

- docker-compose-dev.yml
- docker-compose.yml
- modules/data-analytics/app/clickhouse/models/event/util.py
- modules/data-analytics/app/experimentation/models/event/sql.py
- modules/data-analytics/app/experimentation/models/experiment/experiment_types.py
- modules/data-analytics/app/experimentation/models/experiment/trends_experiment_result.py
- modules/data-analytics/integration_tests/insert_fake_ff_events.py
- modules/data-analytics/integration_tests/insert_fake_metric_events.py
- modules/evaluation-server/src/Domain/Insights/Insight.cs
> fix/insight：interaction between insight and da-server

- README.md
- modules/front-end/src/app/core/components/guide/guide.component.html
**(1) Updated README.md in the root. I simplified the documentation structure.**
**(2) Updated "FeatBit in 3 minutes" documentation page URL in portal's "Get Started" drawer UI.**
> 📖 Updated documentation of readme and get-started

- modules/back-end/src/Api/Controllers/ExperimentController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/Bases/Models/PagedRequest.cs
- modules/back-end/src/Application/FeatureFlags/GetFeatureFlagVariationExptReferences.cs
- modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
- modules/front-end/src/app/core/components/find-rule/targeted-user-table/targeted-user-table.component.ts
- modules/front-end/src/app/core/services/experiment.service.ts
- modules/front-end/src/app/features/safe/experiments/overview/overview.component.html
- modules/front-end/src/app/features/safe/experiments/overview/overview.component.less
- modules/front-end/src/app/features/safe/experiments/overview/overview.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
A modal would be displayed if any reference found
Click on **check experiment** would open the experiment in a new tab as
> ✨ feat(ui): Before removing a variation from a feature flag, verify if it is used by an experiment baseline

- modules/back-end/src/Api/Controllers/EndUserController.cs
- modules/back-end/src/Application/EndUsers/EndUserFlag.cs
- modules/back-end/src/Application/EndUsers/EndUserFlagVm.cs
- modules/back-end/src/Application/EndUsers/EndUserSegment.cs
- modules/back-end/src/Application/EndUsers/EndUserSegmentVm.cs
- modules/back-end/src/Application/EndUsers/GetEndUserFlags.cs
- modules/back-end/src/Application/EndUsers/GetEndUserSegments.cs
- modules/back-end/src/Application/Services/IEvaluator.cs
- modules/back-end/src/Domain/EndUsers/EndUser.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
- modules/back-end/src/Domain/FeatureFlags/RolloutVariation.cs
- modules/back-end/src/Domain/FeatureFlags/UserVariation.cs
- modules/back-end/src/Domain/Segments/Segment.cs
- modules/back-end/src/Domain/Targeting/Condition.cs
- modules/back-end/src/Domain/Targeting/Operator.cs
- modules/back-end/src/Domain/Targeting/OperatorTypes.cs
- modules/back-end/src/Domain/Targeting/SplittingAlgorithm.cs
- modules/back-end/src/Infrastructure/ConfigureServices.cs
- modules/back-end/src/Infrastructure/Targeting/Evaluator.cs
- modules/front-end/src/app/core/components/props-drawer/props-drawer.component.ts
- modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
- modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.spec.ts
- modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.ts
- modules/front-end/src/app/core/services/env-user.service.ts
- modules/front-end/src/app/features/safe/end-users/index/index.component.html
- modules/front-end/src/app/features/safe/end-users/types/user-segments-flags.ts
get end-user's flags and segments
> ✨ get end-user's flags & segments

- modules/back-end/src/Application/Groups/GroupMemberVm.cs
- modules/back-end/src/Application/Policies/PolicyMember.cs
- modules/back-end/src/Infrastructure/Groups/GroupService.cs
- modules/back-end/src/Infrastructure/Policies/PolicyService.cs
Fix issue https://github.com/featbit/featbit/issues/108
> 🐛Fix(api): fixed bug that user name not displayed on team and policy detail page's team tab

- modules/front-end/src/app/core/components/g2-chart/g2-line-chart/g2-line-chart.component.ts
- modules/front-end/src/app/core/components/g2-chart/g2-line-chart/g2-line-chart.ts
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/reporting/reporting.component.ts
> ✨ Feat(ui): user smooth curve for charts

- modules/back-end/src/Api/Controllers/IdentityController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/Identity/ResetPassword.cs
- modules/back-end/src/Application/Identity/ResetPasswordResult.cs
- modules/front-end/package-lock.json
- modules/front-end/src/app/core/services/identity.service.ts
- modules/front-end/src/app/core/services/user.service.ts
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
- modules/front-end/src/app/features/safe/organizations/organizations.module.ts
- modules/front-end/src/app/features/safe/organizations/profile/profile.component.html
- modules/front-end/src/app/features/safe/organizations/profile/profile.component.less
- modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
- modules/front-end/src/app/features/safe/organizations/types/profiles.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
> ✨ reset user password

- .github/workflows/publish-docker-images.yml
- docker-compose-dev.yml
- docker-compose.yml
- modules/front-end/Dockerfile
- modules/front-end/package.json
- modules/front-end/src/assets/env.js
- modules/front-end/src/assets/env.template.js
- modules/front-end/src/environments/environment.prod.ts
- modules/front-end/src/environments/environment.ts
- modules/front-end/src/index.html
> ✨ Feat(ui): added docker compose file for prod

- README.md
- why_featbit.md
1. Add file of Why FeatBit
2. Add Why FeatBit link in README.md
> Updated Readme

- README.md
Added guide reference on top of the readme
> 📖Updated Docs/readme

- modules/back-end/src/Api/Controllers/MemberController.cs
- modules/back-end/src/Application/Members/DeleteMember.cs
- modules/back-end/src/Application/Services/IMemberService.cs
- modules/back-end/src/Infrastructure/Members/MemberService.cs
> 🐛 Implement delete member api

- modules/back-end/src/Api/Controllers/FeatureFlagController.cs
- modules/back-end/src/Application/FeatureFlags/GetInsights.cs
- modules/back-end/src/Application/FeatureFlags/InsightsVm.cs
- modules/back-end/src/Application/Services/IOlapService.cs
- modules/back-end/src/Domain/FeatureFlags/InsightsParam.cs
- modules/back-end/src/Infrastructure/Experiments/OlapService.cs
- modules/front-end/src/app/core/services/env-user.service.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/features/safe/feature-flags/details/details-routing.module.ts
- modules/front-end/src/app/features/safe/feature-flags/details/details.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/details.module.ts
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.less
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/insights/types.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> ✨ feat(ui): rename feature flag reporting tab to insights

- DESIGN.md
- README.md
Hey there. 
I really loved using FeatBit and thought you might be open for not only code but also design contributions. 
Designers would require a little bit of a different context than engineers so I wanted to prepare these docs for you and get the project listed at https://contribute.design to get visibility across designers.
I'm not 100% sure about the flow I'm proposing and the design relevant materials you potentially already have – so feel free to change or propose changes :)
> 📖 docs: add design contribution guidelines

- .design/README.md
Added .design folder and readme.md to let peoples help take FeatBit to another level
> 📖 Added design folder and readme

- README.md
> 📖 Update Docs/readme

- README.md
> 📖Docs/tweetinreadme

- modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 close experiment drawer when user clicks mask

- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/ExperimentMetrics/ArchiveExperiment.cs
- modules/back-end/src/Application/ExperimentMetrics/UpdateExperimentMetric.cs
- modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
- modules/front-end/src/app/core/services/metric.service.ts
- modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.html
- modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 experiment and metric fixes

- README.md
> 📖 Docs/readme

- modules/back-end/src/Api/Controllers/EndUserController.cs
- modules/back-end/src/Application/EndUsers/EndUserFilter.cs
- modules/back-end/src/Application/EndUsers/SearchEndUser.cs
- modules/back-end/src/Domain/EndUsers/EndUser.cs
- modules/back-end/src/Domain/EndUsers/EndUserConsts.cs
- modules/back-end/src/Infrastructure/EndUsers/EndUserService.cs
- modules/front-end/src/app/core/components/target-user/target-user.component.ts
- modules/front-end/src/app/core/services/env-user.service.ts
- modules/front-end/src/app/features/safe/end-users/types/featureflag-user.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
> 🐛 Cannot search end-users

- modules/front-end/src/app/features/safe/audit-logs/index/index.component.html
- modules/front-end/src/app/features/safe/audit-logs/index/index.component.ts
- modules/front-end/src/app/features/safe/audit-logs/types/audit-logs.ts
fix for https://github.com/featbit/featbit/issues/157
> Fix(ui): fixed the targeting user name and segment name not displayed in audit log page bug

- docker-compose.yml
ref: https://docs.docker.com/compose/reference/envvars/#compose_project_name
fixed #163
> 🐛 The docker container name may be conflict

- modules/front-end/src/app/shared/utils/diff/feature-flag.differ.ts
> 🐛 cannot save flag change

- docker-compose-dev.yml
- docker-compose.yml
always use latest featbit image
> 🏗 always use latest image

- infra/mongodb/docker-entrypoint-initdb.d/init.js
there is no reason to use a fixed uuid in our seeding script.
> 🏗 use random uuid when seeding mongodb

- modules/front-end/src/app/core/components/audit-log/audit-log.component.less
- modules/front-end/src/app/features/safe/audit-logs/index/index.component.less
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
style improvement for audit logs
> 🖍 audit log style adjustment

- modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
- modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
- modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
- update setting
- update variation
- toggle flag
- copy flag
> ✨ add more feature flag audit logs

- infra/mongodb/docker-entrypoint-initdb.d/init.js
- modules/back-end/src/Domain/Policies/BuiltInPolicy.cs
> 🐛 keep built-in policy's id consistent

- modules/front-end/src/app/core/components/audit-logs/audit-logs.component.less
- modules/front-end/src/app/core/services/message-queue.service.ts
- modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
When a change happens on either setting or targeting, the other page need to be notified and refreshed
fix for https://github.com/featbit/featbit/issues/184
> 🐛 fix(ui): fixed bug that segment setting page and targeting page not sync

- modules/back-end/src/Api/Controllers/SegmentController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/Segments/DeleteSegment.cs
- modules/back-end/src/Application/Segments/RestoreSegment.cs
- modules/back-end/src/Application/Segments/SegmentFilter.cs
- modules/back-end/src/Application/Services/ISegmentService.cs
- modules/back-end/src/Domain/AuditLogs/AuditLog.cs
- modules/back-end/src/Domain/Segments/Segment.cs
- modules/back-end/src/Infrastructure/Segments/SegmentService.cs
- modules/front-end/src/app/core/services/segment.service.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/segments/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/segments/details/setting/setting.component.less
- modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/segments/index/index.component.html
- modules/front-end/src/app/features/safe/segments/index/index.component.ts
- modules/front-end/src/app/features/safe/segments/index/index.module.ts
- modules/front-end/src/app/features/safe/segments/types/segments-index.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> feat: segment enhancement

- modules/front-end/src/app/core/components/find-rule/find-rule.component.html
- modules/front-end/src/app/core/components/find-rule/find-rule.component.ts
- modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
- modules/front-end/src/app/core/components/find-rule/rule/rule.component.ts
- modules/front-end/src/app/core/components/props-drawer/props-drawer.component.html
- modules/front-end/src/app/core/components/props-drawer/props-drawer.component.ts
- modules/front-end/src/app/core/components/target-user/target-user.component.html
- modules/front-end/src/app/core/components/target-user/target-user.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.html
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Isssue: https://github.com/featbit/featbit/issues/167
Make it possible to create a new user property when editiing rule condition on feature flag or segment targeting page
> feat(ui): create user property when editing targeting rule condition

- modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
fix for https://github.com/featbit/featbit/issues/188
> 🐛 fix: fixed the scroll bar not displaying bug on feature flag history tab

- modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.less
- modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> fix: put the feature flag history tab loader at the center of the page

- infra/mongodb/docker-entrypoint-initdb.d/init.js
- modules/back-end/src/Api/Controllers/EnvironmentSecretController.cs
- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/Environments/AddSecret.cs
- modules/back-end/src/Application/Environments/DeleteSecret.cs
- modules/back-end/src/Application/Environments/RemoveSecret.cs
- modules/back-end/src/Application/Environments/UpdateSecret.cs
- modules/back-end/src/Domain/Environments/Environment.cs
- modules/back-end/src/Domain/Environments/Secret.cs
- modules/back-end/src/Domain/Environments/SecretTypes.cs
- modules/front-end/angular.json
- modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
- modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
- modules/front-end/src/app/core/components/header/header.component.html
- modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
- modules/front-end/src/app/core/services/env-secret.service.ts
- modules/front-end/src/app/core/services/env.service.ts
- modules/front-end/src/app/core/services/permissions.service.ts
- modules/front-end/src/app/core/translations/iam-action.translation.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/iam/components/policy-editor/types.ts
- modules/front-end/src/app/features/safe/organizations/project/project.component.html
- modules/front-end/src/app/features/safe/organizations/project/project.component.less
- modules/front-end/src/app/features/safe/organizations/project/project.component.ts
- modules/front-end/src/app/shared/permissions.ts
- modules/front-end/src/app/shared/types.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
> ✨ feat: support multiple secrets

- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
> 🧹 add feature flag key validation for api

- modules/front-end/src/app/core/components/find-rule/find-rule.component.html
- modules/front-end/src/app/core/components/find-rule/find-rule.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
We've decided to remove this feature, the code needs to be removed
> 🗑️ removed view matched users button on rule definition for feature flag and segment

- modules/front-end/src/app/core/components/audit-log/audit-log.component.ts
- modules/front-end/src/app/core/components/change-list/change-list.component.html
- modules/front-end/src/app/core/components/change-list/change-list.component.less
- modules/front-end/src/app/core/components/change-list/change-list.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fixed audit log displaying bug

- modules/back-end/src/Application/Experiments/CreateExperiment.cs
> 🐛 fixed cannot recreate experiment bug

- README.md
> 📖 Simplify README.md

- README.md
> 📖 README.md typo fix

- README.md
1. Corrected twitter badge's URL address.
> 📖 Readme, corrected twitter badge's URL

- modules/back-end/src/Domain/Targeting/SplittingAlgorithm.cs
- modules/back-end/tests/Domain.UnitTests/Targeting/SplittingAlgorithmTests.cs
- modules/evaluation-server/src/Domain/Core/SplittingAlgorithm.cs
- modules/evaluation-server/tests/Domain.UnitTests/Core/SplittingAlgorithmTest.cs
> ✨ feat: encode splitting key with utf8

- modules/front-end/src/app/core/components/props-drawer/props-drawer.component.html
> 🐛 fix: removed extra space before key in user property preset value editing modal

- README.md
> 📖 doc: README.md typo fix

- CONTRIBUTING.md
Added tutorial of how to contribute
> 📖 doc: how to contribute

- README.md
Added official website links to the readme
> 📖 Added official website links to the readme

- docker-compose.yml
set the docker network to featbit-network-full to distinguish with the docker-compose-partial.yml
> 🏗 infra: change the docker network name

- modules/front-end/src/app/core/components/change-review/change-review.component.html
- modules/front-end/src/app/core/components/change-review/change-review.component.ts
Issue number #235 
- make the comment field optional instead of required according to the issue.
UI
> ✨Update comment to optional UI

- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> fix: run i18n

- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.less
> 🖍 Added padding to segment ref counter button

- modules/evaluation-server/src/Infrastructure/Fakes/FakeCachePopulatingService.cs
- modules/evaluation-server/src/Infrastructure/Fakes/flags.json
- modules/evaluation-server/tests/Application.IntegrationTests/Initialization.cs
- modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoClientDataSyncAsync.verified.txt
- modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoServerDataSyncAsync.verified.txt
- modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/DataSyncTests.cs
- modules/evaluation-server/tests/TestBase/TestBase.csproj
fixed existing tests of the evaluation server
> 🐛fixed evaluation-server tests

- .github/workflows/contribution-log
- .github/workflows/contribution.yml
Whenever a PR is merged, log contributions to a public read only google sheet: https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit?usp=sharing
To make this to work, a label with this format need to be added to PR `points:4`
> 🏗 Added github workflow to log contributions

- .github/workflows/publish-docker-images.yml
- docker-compose-dev.yml
- docker-compose-infra.yml
- docker-compose.yml
> 🏗 Build linux/arm64 image

- .github/workflows/contribution.yml
Added the PR link to the contribution excel file https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540
> 🏗 CI: added pr link to contribution excel file

- .github/workflows/ui-change-validations.yml
Only trigger ui change validations workflow when UI code is changed. I previously the workflow as required as not all changes are UI related
> 🏗CI: trigger ui change validations only when the UI code is changed

- .github/workflows/contribution.yml
- The contributor name was wrong, it gave the repo owner
- Added contributor profile url
> 🏗Fixed contributor name and added contributor profile

- README.md
> 📖 Readme Typo fix

- benchmark/README.md
> 📖 Add data set links

- modules/front-end/src/app/core/components/header/header.component.ts
- modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/iam/groups/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/iam/groups/index/index.component.ts
- modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/iam/policies/index/index.component.ts
- modules/front-end/src/app/features/safe/iam/team/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/iam/team/index/index.component.ts
- modules/front-end/src/app/features/safe/organizations/project/project.component.ts
- modules/front-end/src/app/shared/utils/index.ts
When in a non secure context (neither https nor localhost), clipboard API is not available, the current PR is fix this use case
fixed #247
> 🐛 fix: fixed copy not working bug in a non secure context

- .github/ISSUE_TEMPLATE/contribution_task.md
- Development.md
- README.md
Updated the template for contribution task
> 📖 doc: update contribution task template

- modules/front-end/src/locale/messages.zh.xlf
> Added missing translations

- modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
- modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.less
It was not clear how to invoke a trigger, so I added this tooltip
> ✨feat: added a tooltip for trigger url to tell how to invoke a trigger

- infra/mongodb/docker-entrypoint-initdb.d/init.js
- modules/back-end/src/Application/Resources/ResourceVm.cs
- modules/back-end/src/Domain/Resources/Resource.cs
- modules/back-end/src/Domain/Resources/ResourceType.cs
- modules/back-end/src/Infrastructure/Resources/ResourceService.cs
- modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
- modules/front-end/src/app/core/services/permissions.service.ts
- modules/front-end/src/app/core/services/policy.service.ts
- modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.ts
- modules/front-end/src/app/features/safe/iam/components/policy-editor/resources-selector/resources-selector.component.ts
- modules/front-end/src/app/features/safe/iam/policies/details/permission/permission.component.ts
- modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
- modules/front-end/src/app/features/safe/organizations/project/project.component.html
- modules/front-end/src/app/features/safe/organizations/project/project.component.ts
- modules/front-end/src/app/shared/permissions.ts
- modules/front-end/src/app/shared/policy.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🧹refactor iam

- .github/ISSUE_TEMPLATE/contribution_task.md
The link should point to the contribution sheet.
> 📖 fixed google sheet link

- modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
- modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
This PR aims to resolve errors observed when shutting down the api and evaluation server.
To reproduce
1. dotnet run
2. press ctrl+c to shutdown process
Before
After
refs:
- https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs
- https://github.com/confluentinc/confluent-kafka-go/issues/387#issuecomment-545313461
> 🐛 fix: api & evaluation-server shutdown errors

- modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.ts
Show hide edit button
-----------------------------------
For System Policy
For Customer Policy
> ✨hide edit button for system policies

- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🧹 Regenerate translations

- .github/ISSUE_TEMPLATE/contribution_task.md
When the work is done, ask contributors to merge main into their branch and run i18n
> 📖 Added step to contribution task template

- modules/back-end/src/Api/Controllers/FeatureFlagController.cs
- modules/back-end/src/Application/FeatureFlags/ArchiveFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/DeleteFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/RestoreFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/SetTags.cs
- modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
- modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
- modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
- modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/feature-flags/types/details.ts
Replacing id with key in feature flag URLs makes them more user-friendly and easier for others to use.
> 🧹 refactor: replace id with key in feature flag urls

- modules/back-end/src/Api/Api.csproj
- modules/back-end/src/Api/Authentication/OpenApiAttribute.cs
- modules/back-end/src/Api/Authentication/OpenApiConstants.cs
- modules/back-end/src/Api/Controllers/ApiControllerBase.cs
- modules/back-end/src/Api/Controllers/ApiResponse.cs
- modules/back-end/src/Api/Controllers/BasicController.cs
- modules/back-end/src/Api/Filters/VerifyOpenApiApplicableAttribute.cs
- modules/back-end/src/Api/Setup/ConfigSwaggerOptions.cs
- modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
- modules/back-end/src/Api/Setup/ServicesRegister.cs
- modules/back-end/src/Application/Application.csproj
- modules/back-end/src/Domain/Domain.csproj
- modules/back-end/src/Infrastructure/Infrastructure.csproj
- modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
- modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ModelBinding.verified.txt
- add OpenApi category
- support authentication
- support xml comment
- integrate ReDoc
- example
> ✨ feat: add OpenApi doc support

- modules/back-end/src/Infrastructure/Redis/RedisMessageConsumer.cs
This PR removes the `count` argument from the `LPOP` command in Redis to increase its capability, since **this argument was added starting Redis version 6.2.0**: https://redis.io/commands/lpop/
For example, Azure Cache for Redis **only supports OSS Redis versions 4.0.x and 6.0.x**, which means that FeatBit cannot use it for now. Ref: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview#redis-versions.
> 🧹 refactor: redis lpop usage

- README.md
1. Added Try it Online link & Remove Best Practice link
2. Add 1 new feature in the feature list
3. Add 3 experimental features in the feature list
> 📖 doc: Update README.md

- .github/ISSUE_TEMPLATE/feature_request.md
Used the github default feature request template. 
Two extra items added
- added default label: feature-request
- added the last section: **Is this feature something you're interested in working on?**
> 📖 doc: add feature request template

- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
> fix typo on feature flag's experimentation page

- .all-contributorsrc
- README.md
> 📖 doc: add MichaelYuhe as a contributor for code

- .github/ISSUE_TEMPLATE/contribution-task.md
- Development.md
This pr
- update Development.md
- update contribution task template
> 📖 doc: update Development.md and contribution task template

- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: multi language support for experimentation iteration label

- .all-contributorsrc
- README.md
> 📖 Doc: added fMoro1999 and Exilon as contributors

- docker-compose-pro-dev.yml
- docker-compose-pro.yml
- modules/back-end/src/Domain/Messages/Topics.cs
- modules/data-analytics/app/clickhouse/kafka/kafka_topics.py
- modules/evaluation-server/src/Domain/Core/Topics.cs
> 🧹 refactor: Improve topic names for clarity and consistency

- modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🧹 refactor: make the access token drawer style consistent

- modules/front-end/nginx.conf
This PR adds a basic health check to nginx.conf for the front-end UI container
> Add Health Check to front-end UI container

- .all-contributorsrc
- README.md
> 📖 doc: add brennan and coban as contributors for code

- modules/evaluation-server/src/Domain/Core/Topics.cs
- modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
- modules/evaluation-server/src/Infrastructure/Redis/RedisMessageConsumer.cs
Fixed a critical bug caused by the topic name change pr #345
> 🔥 fix: data change not pushed to sdks

- modules/back-end/src/Application/Identity/ResetPassword.cs
- modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: cannot reset password

- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Resolves #333 Unify Feature Flag On/Off Confirm Messages
> 🧹 refactor: unify feature flag on/off confirm messages

- modules/front-end/src/app/core/services/audit-log.service.ts
- modules/front-end/src/app/core/services/env-setting.service.ts
- modules/front-end/src/app/core/services/env-user-prop.service.ts
- modules/front-end/src/app/core/services/env-user.service.ts
- modules/front-end/src/app/core/services/env.service.ts
- modules/front-end/src/app/core/services/experiment.service.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/core/services/segment.service.ts
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/safe.component.spec.ts
- modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/segments/index/index.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This pr
- solves the envId cache problem
- remove some unused code
> 🐛 fix: env id cache

- modules/front-end/src/app/core/components/prism/prism.component.ts
- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This PR updates the server-side SDKs' code snippets to use the event-url and streaming-url parameters. These parameters are required for the SDKs to work properly.
> 🐛 fix: use event-url & streaming-url on server-side SDKs' code snippets

- modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
> 🐛 fix: make redoc available for production environment

- docker-compose-dev.yml
- docker-compose-pro.yml
- kubernetes/pro/application/api-server-deployment.yaml
- kubernetes/pro/application/ui-deployment.yaml
This pr
- update api service definition in docker-compose-pro.yml
- remove a redundant whitespace character
- fix evaluation url in ui-deployment.yaml
- add Redis__ConnectionString to api-server-deployment.yaml
> 🏗 infra: update api service definition

- README.md
Modified text in the TryItOnline section to provide readers with easier-to-understand information.
> 📖 doc: Add more description for TryItOnline section

- modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
The counter on the dashboard was not correct, it show the count of all organizations
> 🐛 fix: incorrect status count in experiments dashboard

- README.md
In Readme file, I:
1. Refactor section of TryitOnline
2. Added some detail steps in Get Started section
> 📖 doc: add more details to Get Started section

- .github/workflows/publish-docker-images.yml
> Temporary comment publish-docker-images.yml

- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.html
- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This pr
- rename SDK endpoint to Streaming URL
- add event URL to SDK configs
> 🧹 refactor: rename SDK endpoint and add event URL to SDK configs

- .github/workflows/publish-docker-images.yml
> 🏗 infra: restore the docker publish workflow

- modules/front-end/src/app/core/components/find-rule/serve/serve.component.ts
- modules/front-end/src/app/core/components/target-user/target-user.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
- modules/front-end/src/app/features/safe/segments/types/segments-index.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: refresh flag data when flag setting updated

- docker-compose-infra.yml
- docker-compose-pro-dev.yml
- docker-compose-pro.yml
- kubernetes/pro/infrastructure/kafka-pod.yaml
Due to the latest bitnami kafka image turn the kraft on by default, the kafka container cannot be started. The current PR turn kraft off. We will replace zookeeper by KRaft in a future PR
> 🐛 fix: fixed kafka cannot start error

- modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
- modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
- modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
- modules/front-end/src/app/features/safe/get-started/steps/steps.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: the get started page could not create new feature flag

- modules/back-end/src/Application/EndUsers/GetFeatureFlagEndUserList.cs
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> ✨ feat: display variation names instead of valuess in insights page end user table

- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🖍 fix: truncate long variation value with ellipsis

- modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
- modules/front-end/src/app/core/services/project.service.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: current project & env name not updated

- modules/front-end/src/app/core/components/menu/menu.component.less
- modules/front-end/src/app/features/login/login.component.less
New logo seems too big
Before:
After:
> 🖍 style: make logo smaller

- modules/front-end/nginx.conf
We keep seeing malicous scan requests from the internet, the PR return 444 for all unknown requests
> ✨ feat: made UI to return 444 when seeing malicious scan requests

- modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
- modules/evaluation-server/src/Api/Api.csproj
- modules/evaluation-server/src/Api/Program.cs
- modules/evaluation-server/src/Api/Setup/HostBuilder.cs
- modules/evaluation-server/src/Api/Setup/MiddlewaresRegister.cs
- modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
This PR 
- integrate serilog for evaluation server and formatted console output as json
- ignore health check request logging for api project
follow up #446
> ✨ feat: integrate serilog for evaluation server

- modules/front-end/src/app/core/components/header/header.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🐛Fixed user cannot switch to environment even has the access env permission bug

- modules/front-end/src/app/core/services/organization.service.ts
- modules/front-end/src/app/features/safe/onboarding/steps/steps.component.html
- modules/front-end/src/app/features/safe/onboarding/steps/steps.component.less
- modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
- modules/front-end/src/app/shared/types.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This PR enable users to complete the onboarding process successfully.
> 🔥 fix: user cannot complete onboarding

- modules/back-end/src/Application/Bases/ErrorCodes.cs
- modules/back-end/src/Application/Environments/CreateEnvironment.cs
- modules/back-end/src/Application/Environments/IsKeyUsed.cs
- modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
- modules/back-end/src/Application/FeatureFlags/IsFeatureFlagKeyUsed.cs
- modules/back-end/src/Application/Organizations/Onboarding.cs
- modules/back-end/src/Application/Projects/CreateProject.cs
- modules/back-end/src/Application/Projects/IsKeyUsed.cs
- modules/back-end/src/Application/Services/IEnvironmentService.cs
- modules/back-end/src/Application/Services/IFeatureFlagService.cs
- modules/back-end/src/Application/Services/IProjectService.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
- modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
- modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
- modules/back-end/src/Infrastructure/Projects/ProjectService.cs
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
- modules/front-end/src/app/core/guards/auth.guard.ts
- modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
- modules/front-end/src/app/core/services/organization.service.ts
- modules/front-end/src/app/features/safe/onboarding/onboarding.component.html
- modules/front-end/src/app/features/safe/onboarding/onboarding.component.ts
- modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This PR check if key has been used when creating project or environment on the API side.
Some other little change
- remove the feature flag key format check
- skip onboarding if current organization has been initialized
- fix error message not shown when failed to create flag
> ✨ feat: check if key has been used

- modules/front-end/nginx.conf
- modules/front-end/src/environments/environment.prod.ts
- modules/front-end/src/environments/environment.ts
…e machine with docker compose
> 🏗 infra: setting up reverse proxy for API and evaluation server

- modules/front-end/nginx-gateway.conf
- modules/front-end/nginx.conf
add nginx gateway for special usage cases
> 🏗 infra: add nginx gateway

- modules/front-end/nginx.conf
The current PR including:
- set up the cache-control header
- set up gzip
> 🏗 infra: nginx cache control and gzip

- modules/front-end/src/locale/messages.zh.xlf
> 🐛 fix: Chinese translation typo

- modules/front-end/nginx.conf
- modules/front-end/src/app/app-routing.module.ts
> 🧹 enhancement: improve loading time & nginx 404

- modules/front-end/nginx.conf
Refs
- https://github.com/alibaba/Alink/blob/master/webui/tools/web/nginx.conf
- https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-base/nginx.conf
> 🏗 infra: improve nginx settings

- modules/back-end/src/Application/Segments/CreateSegment.cs
- modules/back-end/src/Application/Segments/UpdateSegment.cs
- modules/back-end/src/Domain/Segments/Segment.cs
- modules/back-end/src/Domain/SemanticPatch/FlagInstructionKind.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Models.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.Basic.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.Rule.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.RuleCondition.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.TargetUser.cs
- modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.cs
- modules/back-end/src/Domain/SemanticPatch/SegmentComparer.cs
- modules/back-end/src/Domain/SemanticPatch/SegmentInstructionKind.cs
> ✨ feat: implement segment comparer

- modules/back-end/src/Api/Controllers/FeatureFlagController.cs
- modules/back-end/src/Application/FeatureFlags/DeleteFlagSchedule.cs
- modules/back-end/src/Application/Services/IFlagScheduleService.cs
- modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleService.cs
- modules/front-end/src/app/core/components/change-review/change-review.component.html
- modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
- modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.less
- modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
- modules/front-end/src/environments/environment.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
check this doc
https://docs.featbit.co/docs/feature-workflows/scheduled-flag-changes#deleting-scheduled-flag-changes
> ✨ feat: allow user to remove a pending flag schedule

- modules/front-end/src/app/core/guards/auth.guard.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Reproduce:
1. Log into an account
2. Restore the database
3. Refresh the browser
a blank page would be displayed and we could see the error in the console
> 🐛 fix: organization undefined bug when the database is restored

- docker-compose-pro.yml
- docker-compose.yml
- modules/back-end/README.md
- modules/data-analytics/Readme.md
- modules/evaluation-server/README.md
> 📖 doc: update environment variables

- README.md
1. Added FeatBit's email contact information.
2. Updated license statement section.
> 📖 doc: add contact email

- modules/front-end/src/app/core/components/header/header.component.html
> 🖍 style: use the same icon for enterprise and non enterprise org

- modules/back-end/src/Api/Controllers/TriggerController.cs
- modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
> 🧹 refactor: change feature flag trigger method from put to post

- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
related to https://github.com/featbit/featbit-dotnet-sdk/pull/10
> 🧹 refactor: connect sdk instruction typo

- README.md
> 📖 doc: add commercial license key statements

- .github/ISSUE_TEMPLATE/contribution-task.md
- Development.md
Update Development.md as some information is out of date
> 📖 doc: update Development.md

- modules/front-end/README.md
📖 Documentation: Fixed typing and grammatical errors in modules/front-end/README.md
> 📖 doc: fix typo

- modules/back-end/src/Domain/Organizations/License.cs
- modules/back-end/src/Domain/Organizations/LicenseFeatures.cs
- modules/front-end/src/app/core/components/header/header.component.html
- modules/front-end/src/app/core/components/header/header.component.less
- modules/front-end/src/app/core/components/license/license.component.html
- modules/front-end/src/app/shared/types.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
Previously, we need to list all features in the license. User need to regenerate the license whenever we add a new feature.
To avoid this, the current PR supports **asterisk(*)** for all features.
> ✨ feat: support asterisk in license feature list

- modules/back-end/src/Application/Triggers/RunTrigger.cs
push updates after trigger runs
> 🐛 fix: trigger not pushing updates

- modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
- modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
- modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
- modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.less
- modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
- modules/front-end/src/app/features/safe/experiments/overview/overview.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
code clean and style fixes for #526
> 🧹 refactor: code clean and style fixes

- infra/mongodb/docker-entrypoint-initdb.d/init.js
- kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
- kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
- modules/back-end/src/Domain/Resources/Resource.cs
- modules/back-end/src/Domain/Resources/ResourceTypes.cs
- modules/back-end/src/Infrastructure/Groups/GroupService.cs
- modules/back-end/src/Infrastructure/Resources/ResourceService.cs
- modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.ts
- modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.spec.ts
- modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.ts
- modules/front-end/src/app/core/services/identity.service.ts
- modules/front-end/src/app/core/services/organization.service.ts
- modules/front-end/src/app/core/translations/resource.translation.ts
- modules/front-end/src/app/features/safe/organizations/organization/organization.component.html
- modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
- modules/front-end/src/app/features/safe/organizations/organizations.component.spec.ts
- modules/front-end/src/app/features/safe/organizations/organizations.component.ts
- modules/front-end/src/app/shared/policy.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
The present PR has two purposes:
1.  The account here is previously indeed organization, so it's better to rename it to organization
2. We are going to introduce a new entity: **Account**, it would be a higher level of organization. This would be done in a future PR very soon
This PR brings some breaking changes, be sure to run the following code against your mongodb:
```javascript
const cursor = db.Policies.find({ "statements.resourceType": "account" });
cursor.forEach(doc => {
doc.statements.forEach(statement => {
if (statement.resourceType === "account") {
statement.resourceType = "organization";
statement.resources = statement.resources.map(resource => resource.replace(/^account\//, "organization/"));
}
});
db.Policies.updateOne({ _id: doc._id }, { $set: { statements: doc.statements } …
```
> 🧹 refactor: rename account to organization

- README.md
1. Added FeatBit's usage survey in Readme.
> 📖 doc: add usage survey

- README.md
> 📖 doc: fix broken links in README.md

- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🖍 style: add space around flag name

- modules/evaluation-server/src/Api/Public/SdkController.cs
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
> ✨ feat: add timestamp filter when getting server side flags and segments

- modules/back-end/README.md
- modules/evaluation-server/README.md
add environment variables in README.md
> 📖 doc: add environment variables for api and evaluation server

- modules/front-end/src/app/core/components/guide/guide.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
fix broken links and update contact us email
> 🐛 fix: broken links in get-started page

- modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
- modules/front-end/src/styles-common.less
- modules/front-end/src/styles/nz-input.less
- modules/front-end/src/styles/nz-select.less
> 🖍 style: fix string input style

- modules/back-end/src/Api/Controllers/WebhookController.cs
- modules/back-end/src/Application/Services/IWebhookService.cs
- modules/back-end/src/Application/Webhooks/GetWebhookDeliveryList.cs
- modules/back-end/src/Application/Webhooks/WebhookDeliveryFilter.cs
- modules/back-end/src/Infrastructure/AccessTokens/AccessTokenService.cs
- modules/back-end/src/Infrastructure/Policies/PolicyService.cs
- modules/back-end/src/Infrastructure/RelayProxies/RelayProxyService.cs
- modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs
- modules/back-end/src/Infrastructure/Webhooks/WebhookService.cs
- modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.html
- modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.less
- modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.ts
- modules/front-end/src/app/core/core.module.ts
- modules/front-end/src/app/core/services/webhook.service.ts
- modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.html
- modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.ts
- modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
- modules/front-end/src/styles/icon.less
- modules/front-end/src/styles/nz-drawer.less
- modules/front-end/src/styles/nz-segmented.less
- modules/front-end/src/styles/standards.less
Show webhook delivery logs, follow up #533 
**Screenshots**
> ✨ feat: webhook logs

- modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
- modules/back-end/src/Domain/Webhooks/DataObjectBuilder.cs
- modules/front-end/src/app/core/components/test-webhook-modal/test-webhook.ts
- modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.html
- modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.less
- modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
add webhook change description to webhook callback, follow up #533 
based on #559
> ✨ feat: add webhook change description

- modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
> 🐛 fix: inactive webhooks shouldn't be called

- modules/front-end/src/app/core/components/prism/prism.component.ts
- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.html
- modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> ✨ feat: added Node.js instructions to get started page

- modules/back-end/src/Application/FeatureFlags/OnFeatureFlagDeleted.cs
- modules/back-end/src/Application/Segments/OnSegmentDeleted.cs
We should always run webhook asynchronously
> 🐛 fix: run webhook asynchronously

- README.md
Added integration feature tool links
> 📖 doc: add integration links

- README.md
Updated SDK line in Feature list
> 📖 doc: add SDK links

- modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
- modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
- modules/front-end/src/styles/nz-select.less
Change the layout and controller of the multi-selection
1. When input many contents:
which can be scrolled when it overflows.
2. When the width changes, it can extend.
When width change：
> 🖍 CSS / Styling: Adjust the layout when choose "is one of" in "select operation"

- modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
> 🐛 fix: broken links in UI

- modules/front-end/src/app/core/components/menu/menu.component.html
> 🐛 fix: profile menu link

- README.md
> 📖 doc: add otel integration link

- modules/back-end/src/Api/Program.cs
- modules/evaluation-server/src/Api/Program.cs
these are missing changes for #588
> 🐛 fix: serilog otel integration

- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
This PR fixes a bug in UI Feature Flag Experimentation tab
To reproduce.
1. launch a fresh instance of featbit either manually, using docker-compose.yml or docker-compose-dev.yml
2. create a new project
3. create a flag
4. go to experiments on the left nav
5. create a metric
6. create an experimetn using the new metric and flag
7. click check experiment
8. click start experiment
9. observe the console error in chrome debugging tools
UI
> 🐛 Fix date formatting in experimentation UI to conform with date-fns

- modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
> 🐛Fix date formatting in remote config UI to conform with date-fns

- modules/front-end/src/app/core/components/find-rule/rule/rule.component.ts
> 🐛 Bugfix: When operation is selected, property cannot be selected.

- CONTRIBUTING.md
- Development.md
- kubernetes/pro/Readme.md
> doc: fix typos

- modules/evaluation-server/src/Domain/Shared/IStore.cs
- modules/evaluation-server/src/Infrastructure/Fakes/FakeStore.cs
- modules/evaluation-server/src/Infrastructure/Redis/IRedisClient.cs
- modules/evaluation-server/src/Infrastructure/Redis/RedisClient.cs
- modules/evaluation-server/src/Infrastructure/Store/HybridStore.cs
- modules/evaluation-server/src/Infrastructure/Store/MongoDbStore.cs
- modules/evaluation-server/src/Infrastructure/Store/RedisStore.cs
- modules/evaluation-server/src/Streaming/Connections/ConnectionVersion.cs
enhance redis and mongodb store availability check
> 🧹 refactor: enhance store availability check

- modules/back-end/src/Application/Caches/ICacheService.cs
- modules/back-end/src/Application/Environments/AddSecret.cs
- modules/back-end/src/Application/Environments/CreateEnvironment.cs
- modules/back-end/src/Application/Environments/DeleteEnvironment.cs
- modules/back-end/src/Application/Environments/DeleteSecret.cs
- modules/back-end/src/Application/Environments/OnEnvironmentAdded.cs
- modules/back-end/src/Application/Environments/OnEnvironmentDeleted.cs
- modules/back-end/src/Application/Environments/OnSecretAdded.cs
- modules/back-end/src/Application/Environments/OnSecretDeleted.cs
- modules/back-end/src/Application/Organizations/DeleteOrganization.cs
- modules/back-end/src/Application/Organizations/Onboarding.cs
- modules/back-end/src/Application/Projects/CreateProject.cs
- modules/back-end/src/Application/Projects/DeleteProject.cs
- modules/back-end/src/Application/Projects/OnProjectAdded.cs
- modules/back-end/src/Application/Projects/OnProjectDeleted.cs
- modules/back-end/src/Application/Segments/CreateSegment.cs
- modules/back-end/src/Application/Services/IEndUserService.cs
- modules/back-end/src/Application/Services/IEnvironmentService.cs
- modules/back-end/src/Application/Services/IProjectService.cs
- modules/back-end/src/Domain/Environments/Environment.cs
- modules/back-end/src/Domain/Environments/ResourceDescriptor.cs
- modules/back-end/src/Infrastructure/EndUsers/EndUserService.cs
- modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
- modules/back-end/src/Infrastructure/Organizations/OrganizationService.cs
- modules/back-end/src/Infrastructure/Projects/ProjectService.cs
- modules/back-end/src/Infrastructure/Redis/RedisCacheService.cs
- modules/back-end/src/Infrastructure/Redis/RedisKeys.cs
- modules/back-end/src/Infrastructure/Redis/RedisPopulatingService.cs
Add secret cache to Redis.
Tested Scenario
> ✨ feat: add secret cache

- modules/evaluation-server/src/Api/Public/SdkController.cs
For Client SDKs supporting polling, now we can get the incremental changes by adding a timestamp to the query string, example:
`https://xxx/api/public/sdk/client/latest-all?timestamp=1711096130599`
> ✨ feat: allow client SDKs to get incremental flag changes by API

- modules/evaluation-server/EvaluationServer.sln
- modules/evaluation-server/src/Domain/Shared/IStore.cs
- modules/evaluation-server/src/Infrastructure/Fakes/FakeStore.cs
- modules/evaluation-server/src/Infrastructure/MongoDb/IMongoDbClient.cs
- modules/evaluation-server/src/Infrastructure/MongoDb/MongoDbClient.cs
- modules/evaluation-server/src/Infrastructure/Store/EmptyStore.cs
- modules/evaluation-server/src/Infrastructure/Store/HybridStore.cs
- modules/evaluation-server/src/Infrastructure/Store/MongoDbStore.cs
- modules/evaluation-server/src/Infrastructure/Store/NoneStore.cs
- modules/evaluation-server/src/Infrastructure/Store/RedisStore.cs
- modules/evaluation-server/src/Infrastructure/Store/StoreAvailabilityListener.cs
- modules/evaluation-server/src/Infrastructure/Store/StoreAvailableSentinel.cs
- modules/evaluation-server/src/Infrastructure/Store/Stores.cs
- modules/evaluation-server/src/Infrastructure/Utils/TaskExtensions.cs
- modules/evaluation-server/src/Streaming/DependencyInjection/StreamingBuilderExtensions.cs
- modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
- modules/evaluation-server/tests/Infrastructure.UnitTests/StoreAvailableSentinelTests.cs
- modules/evaluation-server/tests/Streaming.UnitTests/Messages/RequestValidatorTests.cs
Utilize `StoreAvailableSentinel` to avoid unnecessary store availability check
> 🚀 perf: add store availablility check sentinel

- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Add a tooltip when hover the variation name, and remove copy button, when user click the tag they can copy variation value. 
1. Add a tooltip
2. When click the tag, it will be copied
(#582)
> 🐛 Fix: If the variation name is not short, can't see the full name.

- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
> 🖍 style: improve variation item style

- modules/front-end/src/app/core/guards/auth.guard.ts
- modules/front-end/src/app/core/services/workspace.service.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
This is not a common problem (only happens when switching databases), but let's just fix that for better development experience
> 🐛 fix: ui is blank if workspaceId is invalid

- modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
> 🖍 fix: select organization style

- modules/evaluation-server/src/Api/Public/SdkController.cs
- modules/evaluation-server/src/Streaming/Protocol/ClientSdkPayload.cs
- modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoClientDataSyncAsync.verified.txt
Client SDK needs `variationId` and `sendToExperiment` when sending insight messages
> ✨ feat: add `variationId` and `sendToExperiment` field to get client feature flags API

- modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
- modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
- modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
- modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Fixed #626 by adding flag key regex valiation
> ✨ feat: add flag key regex validation

- modules/front-end/src/app/core/components/locale-switcher/locale-switcher.component.less
- modules/front-end/src/app/core/components/menu/menu.component.html
- modules/front-end/src/app/core/components/menu/menu.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🖍 style: fix account menu style

- modules/front-end/src/app/features/login/do-login/do-login.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Update social login hint to be more user-friendly
> 🧹 chore: update social login hint

- modules/evaluation-server/src/Api/Public/SdkController.cs
- modules/evaluation-server/src/Streaming/Protocol/ClientSdkPayload.cs
- modules/evaluation-server/src/Streaming/Protocol/ServerSdkPayload.cs
return 
1. empty result when there is no data change
2. the following structure when there are changes for client side api
```
{
"messageType": "data-sync",
"data": {
"eventType": "full",
"userKeyId": "my-user",
"featureFlags": []
}
}
```
> 🧹 refactor: align get client feature flags API with streaming response format

- modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🧹refactor: change hour format when displaying date

- README.md
> 📖 doc: added react native sdk link to readme

- modules/back-end/src/Api/Controllers/SsoController.cs
- modules/back-end/src/Application/Identity/SsoPreCheck.cs
- modules/back-end/src/Application/Identity/SsoPrecheck.cs
- modules/back-end/src/Application/Services/IWorkspaceService.cs
- modules/back-end/src/Infrastructure/Workspaces/WorkspaceService.cs
- modules/back-end/tests/Application.IntegrationTests/Stubs/TestWorkspaceService.cs
- modules/front-end/src/app/core/services/sso.service.ts
- modules/front-end/src/app/features/login/do-login/do-login.component.ts
- modules/front-end/src/app/shared/types.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
For self-hosted environnment, it's very annoying to provide the workspace key each time a user wants to login with SSO.
The current PR would fill this field by the default workspace, so user no need to worry about this.
> ✨ feat: provide default workspace key for SSO

- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
fixed #652 
- https://g2-v3.antv.vision/zh/docs/manual/tutorial/scale#timecat
- test using: https://g2-v3.antv.vision/en/examples/gallery/line#line9
> 🐛 fix: time format error in experimentation page

- modules/evaluation-server/src/Api/Api.csproj
- modules/evaluation-server/src/Api/Program.cs
- modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
- modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
- modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/DataSyncTests.cs
- modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
- modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
- modules/evaluation-server/tests/Streaming.UnitTests/Connections/ConnectionTypeTests.cs
- modules/evaluation-server/tests/Streaming.UnitTests/Shared/SecretTests.cs
- modules/evaluation-server/tests/Streaming.UnitTests/Shared/TokenNumberTests.cs
- modules/evaluation-server/tests/Streaming.UnitTests/Shared/TokenTests.cs
- modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
- modules/evaluation-server/tests/TestBase/TestBase.csproj
bump package versions
follow up #658
> 🔧 refactor: bump evaluation server package versions

- modules/back-end/deploy/Dockerfile
- modules/back-end/start.sh
- modules/evaluation-server/deploy/Dockerfile
- modules/evaluation-server/start.sh
.NET OTEL instrumentation now add support for arm64. 
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3277
> 🏗 infra: .NET auto instrumentation now support ARM64

- .github/workflows/api-server-validations.yml
- .github/workflows/evaluation-server-validations.yml
- modules/back-end/Directory.Build.props
- modules/back-end/deploy/Dockerfile
- modules/back-end/src/Api/Api.csproj
- modules/back-end/src/Application/Application.csproj
- modules/back-end/src/Domain/Domain.csproj
- modules/back-end/src/Infrastructure/Infrastructure.csproj
- modules/back-end/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
- modules/back-end/tests/Application.UnitTests/Application.UnitTests.csproj
- modules/back-end/tests/Domain.UnitTests/Domain.UnitTests.csproj
- modules/back-end/tests/TestBase/TestBase.csproj
- modules/evaluation-server/Directory.Build.props
- modules/evaluation-server/deploy/Dockerfile
- modules/evaluation-server/global.json
- modules/evaluation-server/perf/Benchmarks/Benchmarks.csproj
- modules/evaluation-server/src/Api/Api.csproj
- modules/evaluation-server/src/Directory.Build.props
- modules/evaluation-server/src/Domain/Domain.csproj
- modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
- modules/evaluation-server/src/Streaming/Streaming.csproj
- modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
- modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
- modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
- modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
- modules/evaluation-server/tests/TestBase/InMemoryFakeLogger.cs
- modules/evaluation-server/tests/TestBase/TestBase.csproj
Reference
- https://github.com/dotnet/runtime/issues/97828
- https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/
> 🏗 fix: multi platform dotnet project docker build hangs

- modules/evaluation-server/src/Api/Api.csproj
- modules/evaluation-server/src/Directory.Build.props
- modules/evaluation-server/src/Domain/Domain.csproj
- modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
- modules/evaluation-server/src/Streaming/Streaming.csproj
> 🏗 fix: arm64 build error

- modules/front-end/src/app/core/components/header/header.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
If user is on detail page of feature flag or segment or other object, when switching environment, user would stay on the detail page which is bug, the current PR reload the whole APP and navigate to home page.
> 🐛 fix: switching environment bug

- modules/front-end/src/app/core/components/change-list/constants.ts
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
- modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
- modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Fixed #650 by adjusting create feature flag page as variation value would be filled according to  variation name
> ✨ feat: fill variation values according to variation type

- modules/front-end/src/app/features/login/do-login/do-login.component.ts
> 🐛 fix: cannot do SSO login when there is no default workspace key

- modules/back-end/src/Application/Projects/GetProjectList.cs
- modules/front-end/src/app/core/services/project.service.ts
We have a lot of projects in FeatBit.  It's difficult to find the correct project in the list and it would be helpful to have the projects sorted alphabetically by name.
> ✨Sort Projects Alphabetically in Project/Env Modal

- modules/data-analytics/app/main/models/statistics/end_user/end_user_statistics.py
- modules/data-analytics/app/main/models/statistics/end_user/sql.py
- modules/front-end/src/app/features/safe/feature-flags/details/insights/types.ts
🚀 change default period from 7D to 30M in Insight page to speedup request.
🐛 fix: End user search return empty list in Feature Flags -> Insights
This BUG only affects **FeatBit Standard**
> 🐛 fix: end user insight search not working

- modules/front-end/src/app/core/components/audit-log/audit-log.component.html
- modules/front-end/src/app/core/components/license/license.component.html
- modules/front-end/src/app/core/components/license/license.component.ts
- modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
- modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
- modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
- modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.html
- modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
- modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
- modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
- modules/front-end/src/app/features/safe/segments/index/index.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
fixed #690 
for G2 mask options, we still need to use `YYYY`, check https://g2-v4.antv.vision/en/docs/api/general/scale#scaleoptionmask
> 🐛 fix: date display bug

- modules/back-end/src/Api/Controllers/FeatureFlagController.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheck.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheckResult.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnvResult.cs
- modules/back-end/src/Application/Segments/GetSegmentByIds.cs
- modules/back-end/src/Application/Services/ISegmentService.cs
- modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
- modules/back-end/src/Domain/Resources/RN.cs
- modules/back-end/src/Infrastructure/Segments/SegmentService.cs
- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.html
- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.less
- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
- modules/front-end/src/app/core/components/segment-creation-modal/segment-creation-modal.component.html
- modules/front-end/src/app/core/core.module.ts
- modules/front-end/src/app/core/services/feature-flag.service.ts
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.less
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles-common.less
- modules/front-end/src/styles/nz-collapse.less
- modules/front-end/src/styles/nz-modal.less
> ✨ feat: copy feature flag v2

- modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
- modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
> 🖍 style: fix select segment style

- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
- modules/front-end/src/app/core/services/project.service.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
caused by [#696 ](https://github.com/featbit/featbit/pull/696/commits/b30404ee864fc2ca1c3a637efa9df40c9b6e4832)
> 🔥fix: load current project environments only when copying feature flags

- modules/data-analytics/app/main/models/statistics/end_user/end_user_statistics.py
- modules/data-analytics/app/setting.py
> 🐛 fix: totalCount should never be None

- docker/composes/docker-compose-infra.yml
- modules/back-end/src/Domain/Utils/ValueStopwatch.cs
- modules/back-end/src/Infrastructure/AppService/InsightsWriter.cs
- modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/InsightService.cs
- modules/back-end/src/Infrastructure/Services/MongoDb/InsightService.cs
also fixed a bug that insights doesn't write to MongoDb
> 🚀 perf: refactor InsightsWriter

- modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheck.cs
- modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheckResult.cs
- modules/back-end/src/Application/Services/IEndUserService.cs
- modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/EndUserService.cs
- modules/back-end/src/Infrastructure/Services/MongoDb/EndUserService.cs
- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.less
- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
- modules/front-end/src/app/core/components/props-drawer/props-drawer.component.html
- modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
create new properties in target environment when copying feature flags
follow up #696
> 🐛 fix: new property not copied to target environment

- modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
- modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
- modules/front-end/src/styles/nz-modal.less
> ✨ feat: copy single feature flag

- modules/front-end/src/app/core/components/header/header.component.ts
- modules/front-end/src/app/core/core.module.ts
- modules/front-end/src/app/core/services/broadcast.service.ts
- modules/front-end/src/app/core/services/identity.service.ts
- modules/front-end/src/app/features/safe/workspaces/organization/organization.component.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
sync the following status between different tabs
- user login/out status
- current environment status
- current organization status
> ✨ feat: sync app status across browser tabs

- README.md
- fixed installation link
- fixed online demo link
> 📖 doc: fixed broken link

- modules/back-end/src/Api/Controllers/AuditLogController.cs
- modules/back-end/src/Api/Swagger/ConfigureSwaggerOptions.cs
- modules/back-end/src/Api/Swagger/Examples/PatchFeatureFlagExamples.cs
- modules/back-end/src/Application/AuditLogs/AuditLogFilter.cs
- modules/back-end/src/Application/Bases/Models/PagedRequest.cs
> [!NOTE]  
> Currently there is no permission control for audit logs
> ✨ feat: openapi for get the audit-log list

- modules/back-end/README.md
- modules/back-end/src/Api/appsettings.Development.json
- modules/back-end/src/Api/appsettings.json
- modules/back-end/src/Infrastructure/ConfigurationExtensions.cs
- modules/back-end/src/Infrastructure/Persistence/EntityFrameworkCore/PostgresOptions.cs
- modules/evaluation-server/README.md
- modules/evaluation-server/src/Api/appsettings.Development.json
- modules/evaluation-server/src/Api/appsettings.json
- modules/evaluation-server/src/Infrastructure/ConfigurationExtensions.cs
- modules/evaluation-server/src/Infrastructure/Persistence/PostgresOptions.cs
> 🏗 infra: add optional Postgres password configuration

- Development.md
>  📖 doc: update development instruction

- modules/evaluation-server/src/Infrastructure/Store/PostgresStore.cs
fixed https://github.com/featbit/featbit-java-sdk/issues/24
~We should also fix it on the java sdk side to allow for the missing “isArchived” field.~
> 🔥 fix: isArchived field is required by Java SDK

- infra/mongodb/docker-entrypoint-initdb.d/v5.0.5.js
- infra/postgresql/docker-entrypoint-initdb.d/v5.0.5.sql
- modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
- modules/front-end/src/app/features/safe/workspaces/organization/organization.component.ts
- modules/front-end/src/app/shared/policy.ts
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
Previously if multi org is granted by licence, any user can create new organizations, but we only want the admin user or any user who is granted with the CreateOrg permmison to be able to create new organizations. 
Current PR added a new permission `CreateOrg` to organization resource type and granted by default to the Admin policy. 
To let current Administrator policy(the built in policy) has the CreateOrg permission, you need to run the following script against your database:
- MongoDB
```
const dbName = "featbit";
print('use', dbName, 'database')
db = db.getSiblingDB(dbName)
const administratorPolicyId = UUID("3e961f0f-6fd4-4cf4-910f-52d356f8cc08")
function getUUIDString() {
return UUID().toString().split('"')[1];
}
const newStatement = {
_id: getUUIDString(),
resourceType: …
```
> ✨ feat: added permission for creating organization

- modules/back-end/README.md
Updated docs about `JWT` section
> 📖 doc: update JWT doc

- .github/dependabot.yml
> 🏗 Configure Dependabot for npm in front-end directory

- docker-compose-mongodb.yml
- modules/back-end/src/Infrastructure/Services/OlapService.cs
- modules/evaluation-server/src/Directory.Build.props
added mongodb docker compose file for reference
> 🏗 infra: mongodb docker compose file

- modules/evaluation-server/src/Directory.Build.props
- modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
- modules/front-end/src/app/core/components/guide/guide.component.html
- modules/front-end/src/app/core/components/segment-creation-modal/segment-creation-modal.component.ts
- modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.ts
- modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
- modules/front-end/src/app/features/safe/get-started/steps/steps.component.html
- modules/front-end/src/app/features/safe/workspaces/project/project.component.html
- modules/front-end/src/locale/messages.xlf
- modules/front-end/src/locale/messages.zh.xlf
ref: 
1. https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/19.0.0
2. https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/18.0.0
affected
- nz-checkbox-group
- card
- segmented
- nzExpandIconPosition
> 🐛 fix: ng-zorro-antd breaking changes

- infra/mongodb/docker-entrypoint-initdb.d/v5.0.5.js
- infra/mongodb/docker-entrypoint-initdb.d/v5.1.0.js
- infra/postgresql/docker-entrypoint-initdb.d/v5.1.0.sql
added migration scripts
**We should merge this PR when we release v5.1.0**
v5.1.0 releated PRs
> 🏗 infra: db migrations scripts for v5.1.0

- modules/data-analytics/Dockerfile
https://github.com/featbit/featbit/actions/runs/17789189326/job/50562503288
> 🐛 fix: da-server build error

- modules/front-end/Dockerfile
fixed build error https://github.com/featbit/featbit/actions/runs/17790131499/job/50565092878
> 🏗 infra: update ui service base image
