featbit/featbit

modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

The project missed some Chinese translations in "Get Started" drawer module. 
1. I completed the empty translations <targets />. 
2. I reexecuted "npm run i18n" to correct linenumbers and source texts in zh translation file.
No related trello card

🐛 Completed zh translation & reexecute npm run i18n

---

modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts

Fix of issue https://github.com/featbit/featbit/issues/90
The real reason is that the feature flag was not fetched yet when loading experiments, so the feature flag id was not available. 
Execute the experiments loading procedure after feature flag is fetched fix the problem

🐛 fix(ui/experimentation): fixed experimentation wrongly loaded into experimentation tab of a feature flag bug

---

docker-compose-dev.yml
modules/front-end/Dockerfile
modules/front-end/src/app/core/components/guide/guide.component.html
modules/front-end/src/app/core/components/guide/guide.component.ts
modules/front-end/src/environments/environment.prod.ts
modules/front-end/src/environments/environment.ts

"3. Try interactive with demo" button in "Quick start guide" is a dynamic link which is composed by :
- Demo's remote server URL (which should be configurable).
- Environment secret of current environment in Portal.
- Evaluation server url which demo can communicate with for its FeatBit SDK.
So:
1. I modified the code which recomposes the link of "3. Try interactive with demo" button.
2. I added configurable params in environment.ts and environment.prod.ts. Because demo's url and evaluation server are different and depend on how users construct their network.
3. I updated docker-compose-dev.yml file that we can pass two enviroment's params from docker-compose.
PS:
I also added the number before each "Get Started" item. This is feedback from testing users.

📖 🏗 🔧Enable access of interactive demo hosted in remote server

---

modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
modules/front-end/src/app/core/services/identity.service.ts

After regenerated data in mongodb, if we refresh the UI, we would see a blank page, that's because the org the current user loged in doesn't exist any more (id changed) . 
The current PR forces to logout the user in this situation.

🐛 force to logout after reinitialized mongodb data

---

modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/FeatureFlagVm.cs
modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs

It may happen, that we forget the purpose of a feature flag. A description could be helpful.
I've added the 'description' property to provide the Front-End the possibility to declare a description on creating/updating a feature flag and also to display it.
Solved issue: #243 
Related issues: 
Front-End: #257 #237 #236

✨ feat: (api) add feature flag description

---

modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

✨ Add description field to new feature form

---

modules/front-end/src/app/features/safe/experiments/overview/overview.component.less
modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
modules/front-end/src/app/features/safe/feature-flags/types/details.ts
modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.less
modules/front-end/src/app/features/safe/iam/groups/index/index.component.less
modules/front-end/src/app/features/safe/iam/policies/index/index.component.less
modules/front-end/src/app/features/safe/iam/team/index/index.component.less
modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf
modules/front-end/src/styles-common.less
modules/front-end/src/variables.less

fixed #236 
Read view
Editing view

✨ feat: added description field to feature flag setting page

---

modules/front-end/src/app/core/components/header/header.component.html
modules/front-end/src/app/core/components/header/header.component.less
modules/front-end/src/app/core/components/header/header.component.ts
modules/front-end/src/app/core/services/feedback.service.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

✨ feat: implemented a feature to allow users to send feedback to featbit maintainer

---

modules/back-end/src/Api/Controllers/EnvironmentController.cs
modules/back-end/src/Application/Bases/ErrorCodes.cs
modules/back-end/src/Application/EndUsers/GetFeatureFlagEndUserList.cs
modules/back-end/src/Application/Environments/CreateEnvironment.cs
modules/back-end/src/Application/Environments/IsKeyUsed.cs
modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/GetInsights.cs
modules/back-end/src/Domain/Environments/Environment.cs
modules/back-end/src/Infrastructure/Projects/ProjectService.cs
modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
modules/front-end/src/app/core/components/env-drawer/env-drawer.component.less
modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
modules/front-end/src/app/core/components/header/header.component.html
modules/front-end/src/app/core/components/header/header.component.less
modules/front-end/src/app/core/components/header/header.component.ts
modules/front-end/src/app/core/services/env.service.ts
modules/front-end/src/app/core/services/project.service.ts
modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
modules/front-end/src/app/features/safe/organizations/project/project.component.html
modules/front-end/src/app/features/safe/organizations/project/project.component.less
modules/front-end/src/app/features/safe/organizations/project/project.component.ts
modules/front-end/src/app/shared/types.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

- Added the key field to environment
- Added current tag to current project and env

✨ feat: add environment key

---

modules/evaluation-server/src/Api/Public/SdkController.cs
modules/evaluation-server/src/Domain/Services/IDataSyncService.cs
modules/evaluation-server/src/Infrastructure/Services/DataSyncService.cs

request with
```shell
curl -H "Authorization: the-env-secret" http://localhost:5100/api/public/sdk/server/latest-all
```
example output
```json
{
"messageType":"data-sync",
"data":{
"eventType":"full",
"featureFlags":[
{
"envId":"1331554d-98c4-41fe-ade4-68e6f5eeb54a",
"name":"hello world",
"key":"hello-world",
"variationType":"boolean",
"variations":[
{
"id":"bbe8f444-090e-4a3b-99fa-b487bab424aa",
"value":"true"
},
{
"id":"cf8f9626-0d6f-4d05-a98f-8c3a50c85d0f",
"value":"false"
}
],
"targetUsers":[
],
"rules":[
],
"isEnabled":true,
"disabledVariationId":"cf8f9626-0d6f-4d05-a98f-8c3a50c85d0f",
"fallthrough":{
"dispatchKey":null,
"includedInExpt":true,
"variations":[
{
"id":"bbe8f444-090e-4a3b-99fa-b487bab424aa",
"rollout":[
0,
1
],
"exptRollout":1
}
]
},
"exptIncludeAllTargets":true, …
```

✨ feat: add api to retrieve the latest data for the server and client sdks

---

modules/data-analytics/Dockerfile
modules/data-analytics/docker-entrypoint.sh

CHECK_DB_LIVNESS(true by default) is marked whether to check database liveness when da server start up. If your mongo or clickhouse is a external SAAS service, **set this value false**.

feat: add CHECK_DB_LIVNESS params

---

README.md

“contribution badge” position was coded incorrectly. I fixed the bug of that.
Bug before fixing:
After fixing:

📖 doc: fix contribution badge

---

modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
modules/front-end/src/app/features/safe/end-users/index/index.component.html
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

- Change text from "Feature flags and segments" to "Evaluate on flags and segments"
- Remove the text "Feature flags and segments: " from the user segment flags drawer title
- Update the Chinese translation to 评估开关和用户组
Fixed #337

🧹 refactor: updated "Feature flags and segments" label to more concise one

---

modules/front-end/src/app/core/components/find-rule/serve/serve.component.less

🐛 Solves #347 [Bug]: Content of number input is not vertically centered

Vertically align content of number input

---

modules/front-end/src/app/core/components/guide/guide.component.html
modules/front-end/src/app/core/components/prism/prism.theme.less
modules/front-end/src/app/features/safe/get-started/get-started.component.less
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

Fixes #368 
In get started page, when the code block for the second step is too long, the grid blowout is triggered, the current PR is to fix this issue. Check the blog: https://css-tricks.com/preventing-a-grid-blowout/
I also decreased the font-size of the code to make it the same size as other text in the page and this would also make the grid blowout less likely to happen.
After fix, when a code block is too long, a horizontal scrollbar is displayed at the bottom of the code block

🐛 fix: get started module layout

---

modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

https://github.com/featbit/featbit/assets/80916997/bdabb12f-09c6-4d63-aa90-5f64fdbf9870
I added nz-tooltip attribute to all variants and wrote a new function to show multiple variants with their title and content
fixed #356

🐛 fix: display complete information when hovering on variants (#356)

---

modules/back-end/src/Application/Bases/ErrorCodes.cs
modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/IsFeatureFlagKeyUsed.cs
modules/back-end/src/Application/Services/IFeatureFlagService.cs
modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
modules/front-end/src/app/features/safe/feature-flags/index/index.component.html

This pr fix this bug by:
- Added feature flag key validation before creating it in the API
- Enabled the "Save" button only after successful validation

🐛 fix: user can create duplicate key

---

modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.less
modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf
modules/front-end/src/styles-common.less

This pull request focuses on resolving some style issues present on our portal site. The issues include:

🖍 style: address styling issues on portal site

---

modules/back-end/src/Application/FeatureFlags/GetInsights.cs
modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts

Instead of showing variation values, we will now display the corresponding variation names.

✨ feat: display variation names instead of values in insights page

---

modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

This pull request addresses an issue in the feature flag index page that occurs when loading the page with a query string. 
The query string is used to instantiate the feature flag filter, but the extracted values are treated as strings, causing type mismatch problems. For example, when the query string contains `?isArchived=false`, the value of `filter.isArchived` is parsed as a string "false", so conditional checks like `*ngIf="filter.isArchived"` will evaluate to true, which is not the intended behavior.

🐛 fix: type mismatch in instantiating feature flag filter from query string

---

modules/front-end/src/app/core/components/header/header.component.html
modules/front-end/src/app/core/components/header/header.component.less
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

Add a target=_blank to the link, merging the branch with the main and run the npm i18n command before commit
Issue #395

✨ UI feat: add icon on header that redirect on the docs

---

modules/front-end/src/app/app-routing.module.ts
modules/front-end/src/app/app.module.ts
modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
modules/front-end/src/app/core/services/identity.service.ts
modules/front-end/src/app/features/safe/end-users/details/details.resolver.ts
modules/front-end/src/app/features/safe/onboarding/onboarding.component.ts
modules/front-end/src/app/features/safe/safe.component.ts

Resolve is deprecated and will be removed in Angular 17, the prefered way is the ResolveFn

🧹 refactor: replace class-based resolvers with functional resolvers

---

modules/front-end/nginx.conf

This pull request addresses an issue where the UI fails to start in Azure App Service due to the use of a 444 status code for unknown requests. To resolve this, the PR updates the response to return a 404 status code instead.
Reference: [Azure App Service - Configure Robots.txt](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/app-service-web-configure-robots933456.md)

🔥 hotfix: ui cannot start in azure app service

---

modules/front-end/src/app/core/guards/auth.guard.ts
modules/front-end/src/app/core/services/identity.service.ts
modules/front-end/src/app/core/services/organization.service.ts
modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

For an authenticated user, if he refreshes the navigator, then go to the organization page, an error would happen in the console indicating that the curent org is undefined.

🐛 fix: organizations are not loaded after user refresh the page

---

infra/mongodb/docker-entrypoint-initdb.d/init.js
kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
modules/front-end/src/app/core/components/header/header.component.html
modules/front-end/src/app/core/components/header/header.component.ts
modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.ts
modules/front-end/src/app/core/guards/auth.guard.ts
modules/front-end/src/app/core/services/permissions.service.ts
modules/front-end/src/app/core/services/project.service.ts
modules/front-end/src/app/features/safe/organizations/project/project.component.html
modules/front-end/src/app/features/safe/organizations/project/project.component.ts
modules/front-end/src/app/shared/policy.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

The following changes:
- Rename ListProjects to CanAccessProject: can be applied to both general and specific projects
- if applied to general projects: can access to all projects
- if  applied to a specific project: can access to a specific project
Projects without CanAccessProject action granted won't be displayed in the UI
- Remove ListEnvironments: if a user can access a project, he can access to all its envs 
except the envs whose CanAccessEnv permission is explicitly denied
- Rename AccessEnvs to CanAccessEnv 
This PR brings a breaking change, need to update the MongoDb with the following scripts:
- Rename the action **ListProjects** to **CanAccessProject**
```
db.Policies.updateMany(
{
"statements.actions": "ListProjects"
},
{
$set: {
"statements.$[elem].actions.$[action]": …
```

🧹 refactor: change the way we control project and env permissions

---

modules/front-end/nginx.conf

Currently when a non existing resource file (image, css, js) is requested, nginx would log a 404 along with an error. This behavior would trigger an alarm. The current PR force nginx only log the 404 and remove the error log

🏗 infra: UI log 404 instead of error when non-existing image, css and js files are requested

---

modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.ts
modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
modules/front-end/src/app/core/components/member-drawer/member-drawer.component.html
modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.ts
modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
modules/front-end/src/app/features/safe/organizations/profile/profile.component.html
modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

🧹 refactor: ngModelChange usages

---

README.md

Once this PR has been merged, we can remove @all-contributors
preview: https://github.com/featbit/featbit/tree/doc/update-contributors

📖 doc: update contributors

---

modules/back-end/src/Domain/SemanticPatch/FlagComparer.cs

If we only update one condition's op or value, current code would not create any FlagInstructions, but a **UpdateRuleCondition** instruction should be created in this case.
Reproduce:
update rule condition: name is true => name is false

🐛 fix: update rule condition value didn't generate flag instructions

---

modules/back-end/src/Domain/SemanticPatch/FlagComparer.cs

The FlagComparer would always return UpdateDefaultRuleVariationOrRolloutInstruction if both original and new values are percentage rollouts even they have the same value

🐛 fix variation rollout compare bug

---

modules/front-end/src/app/core/components/audit-log/audit-log.component.html
modules/front-end/src/app/core/components/change-list/change-list.component.ts
modules/front-end/src/app/core/components/change-review/change-review.component.html
modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html

Previously, when creating or deleting a feature flag, we don't generate any instructions, but the change-list component was still initiated which causes an error. 
The current fix does not instantiate the component if no instructions generated.

🐛 fix: auditlog parse json error

---

modules/evaluation-server/src/Api/Properties/launchSettings.json
modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
modules/evaluation-server/src/Api/appsettings.Development.json
modules/evaluation-server/src/Api/appsettings.json
modules/evaluation-server/src/Domain/Shared/IStore.cs
modules/evaluation-server/src/Infrastructure/Fakes/FakeStore.cs
modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
modules/evaluation-server/src/Infrastructure/MongoDb/BsonDocumentExtensions.cs
modules/evaluation-server/src/Infrastructure/MongoDb/IMongoDbClient.cs
modules/evaluation-server/src/Infrastructure/MongoDb/MongoDbClient.cs
modules/evaluation-server/src/Infrastructure/MongoDb/MongoDbOptions.cs
modules/evaluation-server/src/Infrastructure/Redis/IRedisClient.cs
modules/evaluation-server/src/Infrastructure/Redis/RedisClient.cs
modules/evaluation-server/src/Infrastructure/Redis/RedisMessageConsumer.cs
modules/evaluation-server/src/Infrastructure/Redis/RedisMessageProducer.cs
modules/evaluation-server/src/Infrastructure/Store/HybridStore.cs
modules/evaluation-server/src/Infrastructure/Store/MongoDbStore.cs
modules/evaluation-server/src/Infrastructure/Store/RedisStore.cs
modules/evaluation-server/src/Streaming/DependencyInjection/StreamingBuilderExtensions.cs
modules/evaluation-server/tests/Application.IntegrationTests/TestApp.cs

Currently, our evaluation server depends on Redis store only, this PR allows us to fallback to use MongoDB store when Redis store is unavailable

✨ feat: fallback to mongodb when redis is unavailable

---

modules/back-end/src/Infrastructure/Bases/MongoDbService.cs
modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
modules/back-end/src/Infrastructure/Groups/GroupService.cs
modules/back-end/src/Infrastructure/Members/MemberService.cs
modules/back-end/src/Infrastructure/Projects/ProjectService.cs

For improved compatibility with CosmosDB, use CountAsync instead of AnyAsync. Thanks @Erik247ts for pointing this out.
fixed #513

🧹 refactor: replace AnyAsync with CountAsync

---

modules/back-end/src/Application/AuditLogs/GetAuditLogList.cs
modules/back-end/src/Application/Caches/ICacheService.cs
modules/back-end/src/Application/FeatureFlags/ArchiveFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/DeleteFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/OnFeatureFlagChanged.cs
modules/back-end/src/Application/FeatureFlags/OnFeatureFlagDeleted.cs
modules/back-end/src/Application/FeatureFlags/PatchFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/RestoreFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/SetTags.cs
modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
modules/back-end/src/Application/Segments/ArchiveSegment.cs
modules/back-end/src/Application/Segments/CreateSegment.cs
modules/back-end/src/Application/Segments/DeleteSegment.cs
modules/back-end/src/Application/Segments/OnSegmentChange.cs
modules/back-end/src/Application/Segments/OnSegmentDeleted.cs
modules/back-end/src/Application/Segments/PatchSegment.cs
modules/back-end/src/Application/Segments/RestoreSegment.cs
modules/back-end/src/Application/Segments/UpdateSegment.cs
modules/back-end/src/Application/Triggers/RunTrigger.cs
modules/back-end/src/Domain/AuditLogs/AuditLog.cs
modules/back-end/src/Domain/AuditLogs/DataChange.cs
modules/back-end/src/Domain/Triggers/Trigger.cs
modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleWorker.cs
modules/back-end/src/Infrastructure/Redis/RedisCacheService.cs

This new way helps us eliminate more code and makes it easier to maintain. In addition to this, this PR also deletes the segment cache when a segment is deleted.

🧹 refactor: change the way audit logs are written

---

modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf
modules/front-end/src/styles-common.less

Length of selection item content of nz-select component are extended so segment titles wouldn't exceed its limit easily
fixed #506

🖍 style: extend length of selection item content of nz-select component

---

modules/back-end/src/Api/appsettings.Development.json
modules/back-end/src/Api/appsettings.json
modules/back-end/tests/Application.IntegrationTests/Snapshots/KafkaConfigTests.DefaultProducerConsumerConfig.verified.txt
modules/evaluation-server/src/Api/appsettings.Development.json
modules/evaluation-server/src/Api/appsettings.json

Since we store offset manually
https://github.com/featbit/featbit/blob/95c0b568b9f67cc1a417a0b5caf6a757c13ecb13/modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs#L89-L104
https://github.com/featbit/featbit/blob/95c0b568b9f67cc1a417a0b5caf6a757c13ecb13/modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs#L86-L100
Enable auto offset store will cause the following exception
```json
{
"@t":"2023-11-10T06:02:36.8948936Z",
"@mt":"Exception occurred when store offset.",
"@l":"Error",
"@x":"Confluent.Kafka.KafkaException: Local: Invalid argument or configuration\n   at Confluent.Kafka.Impl.SafeKafkaHandle.StoreOffsets(IEnumerable`1 offsets)\n   at Confluent.Kafka.Consumer`2.StoreOffset(TopicPartitionOffset offset)\n   at …
```

🐛 fix: auto offset store should be disabled by default

---

modules/data-analytics/app/__init__.py
modules/data-analytics/app/health/__init__.py
modules/data-analytics/app/health/views.py

This PR adds discrete health check endpoints to the data analytics server at
/health/readiness & /health/liveness
This makes the server consistent with the api and evaluation servers and is helpful to remove noise when filtering traces.
To test run use docker-compose-dev.yml
`docker compose --project-directory . -f ./docker/composes/docker-compose-dev.yml up --build -d `
Then using a browser navigate to http://localhost:8200/health/liveness and http://localhost:8200/health/readiness

✨ feat: add discrete health checks to da-server

---

.github/workflows/publish-docker-images.yml

Now, the latest image will be built only if the GitHub Action runs from the main branch.
An example run can be viewed here: https://github.com/featbit/featbit/actions/runs/6972375512/job/18974409187

🏗 infra: build latest image only if github action runs from main branch

---

.github/workflows/publish-docker-images.yml

This PR
- Always run publish image GitHub Action manually since we need to decide whether to publish latest image
- Make publish-docker-image.yml simpler
- Improving the workflow speed; previously taking 45 minutes, the process now completes in just 22 minutes.
Refer [this](https://github.com/featbit/featbit/actions/runs/7043363396) to check out an example run. Additionally, compare the performance with a previous run (v3.0.0) [here](https://github.com/featbit/featbit/actions/runs/6906276351).

🏗 infra: refactor publish-docker-images.yml

---

modules/back-end/src/Api/appsettings.Development.json
modules/back-end/src/Api/appsettings.json
modules/back-end/src/Infrastructure/Infrastructure.csproj
modules/back-end/src/Infrastructure/Redis/RedisMessageProducer.cs
modules/back-end/tests/Application.UnitTests/Identity/IdentityServiceTests.cs
modules/evaluation-server/src/Infrastructure/Infrastructure.csproj

To fix some vulnerabilities.
Note that the `System.IdentityModel.Tokens.Jwt` introduce a breaking change that could negatively impact our users.
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2072
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IDX10720

🔧 deps: bump dependency versions

---

modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts

Previously, when we create an experiment, the month was displayed as a random number, this is due to migration from momentjs to date-fns, and the format string was not correct. The current PR fixed this problem.

🐛 fix: fixed date formatting bug

---

modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.html

🖍 fix: webhook events tooltip style

---

modules/back-end/src/Infrastructure/Users/UserService.cs

I noticed this when user names were not populated by default.
It was not possible to be used as a way to notify my team of who made the change.
If a user's name is not populated (i.e. an empty string), webhook integrations will not have any record of who performed the change, reducing their effectiveness as notifications that can be followed up on.
1. Clear out your user name.
2. Set up and enable a [webhook integration for a feature flag](https://docs.featbit.co/integrations/webhooks).
3. Use the `operator` variable in the body's template.
4. Trigger the webhook to fire with a real request (Note: The Live Debug feature will not work, as it will always use "Webhook tester" for `operator`).
5. Observe that the value used for the `operator` falls back to your email.

✨ feat: Improve operator fallback logic for empty strings

---

modules/data-analytics/app/experimentation/models/experiment/experiment_types.py

check min required sample size in ABTesting 
fixed #654

🐛 fix: division by zero on numeric metrics

---

infra/mongodb/docker-entrypoint-initdb.d/init.js
kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
kubernetes/standard/infrastructure/mongodb-init-configMap.yaml

Added MongoDB indexes to all relevant tables that are queried with a particular sorting key.
This improves performance, but is not actually the reason I made this change. This PR adds support for running on Azure CosmosDB for MongoDB.
Azure CosmosDB for MongoDB requires that indexes exist when querying using sorting keys, so before we added these to our setup, it would error when attempting to query the database.
Helm chart PR: https://github.com/featbit/featbit-charts/pull/40

🚀 perf: add mongodb indexes

---

modules/back-end/src/Application/Application.csproj
modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
modules/back-end/src/Domain/Environments/ResourceDescriptor.cs

This PR fixes environment filtering for webhooks.  
To Test Webhooks.
1. Create a project
2. Create more than one environment
3. Create a Webhook, select the project and add one of the environments, select all "Feature Flag" events
4. Save the webhook
5. Make sure the webhook is active
6. Create or manipulate flags in the environment that is in scope
7. View the Logs for the webhook
8. Observe that the webhook was fired for environments that are in scope of the webhook
9. switch to an environment that is not in scope
10. Create or manipulate flags in the environment that is not in scope
11. View the Logs for the webhook
12. Observe that the webhook was not fired for environments that are not in scope of the webhook
1. Create a project or use and existing project
2. Create more than one …

🐛 fix: webhooks are not filtered by scope

---

modules/front-end/README.md
modules/front-end/src/app/core/components/header/header.component.ts

This PR fixes a bug introduced by PR 676.  Prior to 676 changing environments or projects usign the modal presented by clicking the header would navigate users to teh feature flags view regardless of where they were in the applicaiton at the time.  This was not desired as a user may be viewing segments and intended to remain on that view when they switched environments or projects.  The PR to fix this inadvertently causes the browser to show a 404 when another project or environment is selected because the locale prefix is removed from the url. This PR fixes that issue.
To test:
1. Create multiple projects and environments and flags or use an existing installation that has these attributes.
2. Navigate the feature flag view
3. Click on the header and select a different environment.
4. …

🐛 fix: switch project/env results in a 404

---

modules/back-end/src/Application/Webhooks/CreateWebhook.cs
modules/back-end/src/Application/Webhooks/SendWebhook.cs
modules/back-end/src/Application/Webhooks/UpdateWebhook.cs
modules/back-end/src/Application/Webhooks/WebhookBase.cs
modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
modules/back-end/src/Application/Webhooks/WebhookVm.cs
modules/back-end/src/Domain/Utils/JsonExtensions.cs
modules/back-end/src/Domain/Webhooks/Webhook.cs
modules/back-end/src/Domain/Webhooks/WebhookDelivery.cs
modules/back-end/src/Domain/Webhooks/WebhookRequest.cs
modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs
modules/front-end/src/app/core/components/test-webhook-modal/test-webhook-modal.component.ts
modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.html
modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.less
modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.ts
modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

Implemented optional prevention of empty webhook payloads as described in #678.
It seems that I cannot add the labels: UI, API
- Create two feature flags in an environment/project scope
- e.g. keys like `feature-flag-1` and `feature-flag-2`
- Create a webhook
- Use a valid URL for an API you can verify is being hit or not
- Use the same project/environment scope as the feature flags
- Select only the "Toggled" Feature Flag event (though other events should also work)
- Use a custom payload template that gives an non-empty request for one of the feature flag keys, e.g.:
```
{
    {{#eq data.object.key "feature-flag-1"}}
    "featureFlagKey": "{{ data.object.key }}"
    {{/eq}}
}
```
- Check the "Prevent empty payloads from being sent" checkbox
- Ensure that the Active checkbox is selected …

✨feat: optionally prevent empty webhook payloads

---

modules/evaluation-server/src/Infrastructure/MQ/Postgres/PostgresMessageConsumer.cs

fixed els postgres consumer will not use the optional password
related to #743

🐛 fix: postgres consumer doesn't use optional password

---

modules/back-end/start.sh
modules/evaluation-server/start.sh

How to test
1. build the local images
```bash
cd modules/back-end
docker build --progress plain -f ./deploy/Dockerfile -t featbit/api:local .
cd modules/evaluation-server
docker build --progress plain -f ./deploy/Dockerfile -t featbit/evaluation-server:local .
```
2. create `docker-compose-local.yml` in `docker/composes` folder with the following content
```yml
name: featbit-local
services:
api-server:
image: featbit/api:local
container_name: api-local
build:
context: ./modules/back-end
dockerfile: ./deploy/Dockerfile
environment:
- SSOEnabled=true
- DbProvider=Postgres
- MqProvider=Redis
- CacheProvider=Redis
- Postgres__ConnectionString=Host=postgresql;Port=5432;Username=postgres;Password=please_change_me;Database=featbit
depends_on:
- postgresql
- redis
ports:
- "5000:5000"
networks:
- …
```

🏗 infra: shutdown container gracefully

---

infra/mongodb/docker-entrypoint-initdb.d/init.js
infra/postgresql/docker-entrypoint-initdb.d/c_seed_data.sql
modules/back-end/src/Domain/Resources/Resource.cs
modules/back-end/src/Domain/Resources/ResourceTypes.cs
modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/ResourceService.cs
modules/back-end/src/Infrastructure/Services/MongoDb/ResourceService.cs
modules/front-end/src/app/features/safe/workspaces/workspace/workspace.component.html
modules/front-end/src/app/features/safe/workspaces/workspace/workspace.component.ts
modules/front-end/src/app/shared/policy.ts
modules/front-end/src/locale/messages.xlf
modules/front-end/src/locale/messages.zh.xlf

Previously everyone with access to FeatBit can modify the workspace settings, which is dangerous for the system. For example if someone with little knowledge with the SSO resets the SSO with invalid values, the SSO would stop to work. 
Current PR protect the modification of workspace settings with IAM policy, including:
- General settings
- License settings
- SSO settings
The PR added a new Resource Type: `Workspace` and three new actions: `UpdateWorkspaceGeneralSettings`, `UpdateWorkspaceLicense` and `UpdateWorkspaceSSOSettings` 
To let current Administrator policy(the built in policy) has these permission, you need to run the following script against your database:
- MongoDB
```js
db.Policies.updateOne(
{
_id: UUID("3e961f0f-6fd4-4cf4-910f-52d356f8cc08"),
"statements.resourceType": { …
```

✨ feat: protect workspace with IAM permissions

---

modules/front-end/Dockerfile
modules/front-end/docker-entrypoint.sh

This pull request makes a small adjustment to the build output path in the Dockerfile, ensuring that the correct frontend assets are copied to the Nginx directory.
* Updated the `COPY` command in `modules/front-end/Dockerfile` to copy from `dist/featbit/browser/` instead of `dist/featbit/`, ensuring the correct build output is used for deployment.

🐛 fix: incorrect path for copying build artifacts

---

docker-compose-mongodb.yml
docker-compose-pro.yml
docker-compose-standard.yml
docker-compose.yml
docker/composes/docker-compose-dev-postgres-clickhouse.yml
docker/composes/docker-compose-dev-postgres.yml
docker/composes/docker-compose-dev.yml
docker/composes/docker-compose-kafka-3-brokers-clickhouse-3-shards.yml
docker/composes/docker-compose-otel.yml
docker/composes/docker-compose-pro-dev-HA-kafka.yml
modules/front-end/Dockerfile
modules/front-end/docker-entrypoint.sh
modules/front-end/nginx.base_href.conf
modules/front-end/nginx.conf

If you ever need to run UI from a path different that the default value, you can now pass the `BASE_HREF` environment variable to the UI. With this, the navigator could successfully find the assets files.
Ex. You wanna run the UI from:
```https://yourdomain.com/dev/svc-featbit-poc/latest/featbit-ui-server/en```
Then just do
```BASE_HREF=/dev/svc-featbit-poc/latest/featbit-ui-server/```
You can modify the value of the environment variable in the docker compose file you are using

✨ feat: make the base_href configurable in the UI
